#!/bin/bash -l

#SBATCH -A uppmax2025-3-3
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 4
#SBATCH -t 00:30:00
#SBATCH -J fastqc_short_DNA
#SBATCH --mail-type=ALL
#SBATCH --mail-user lukasafgeijerstam@gmail.com
#SBATCH --output=%x.%j.out

# Load modules
module load bioinfo-tools
module load FastQC

# Define inputs and output directory
output_dir="/home/lukasa/Genome_analysis_project/raw_data/01-quality_control"

# Run FASTQC
for file in {65,71}; 
do
    fastqc -o $output_dir --threads 4 "/home/lukasa/Genome_analysis_project/raw_data/DNA_reads/short_reads/SRR244130${file}_1.fastq.gz"
    fastqc -o $output_dir --threads 4 "/home/lukasa/Genome_analysis_project/raw_data/DNA_reads/short_reads/SRR244130${file}_2.fastq.gz"
done