#!/bin/bash -l

#SBATCH -A uppmax2025-3-3
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 8
#SBATCH -t 01:00:00
#SBATCH -J snp_identification
#SBATCH --output=%x.%j.out

# Load modules
module load bioinfo-tools
module load MUMmer

set -e

R7_assembly="/home/lukasa/Genome_analysis_project/04-mapping_polishing/polished_assembly_72.fasta"
HP126_assembly="/home/lukasa/Genome_analysis_project/04-mapping_polishing/polished_assembly_66.fasta"

# Align HP126 assembly to R7 assembly
nucmer --threads 8 --prefix=R7_vs_HP126 $R7_assembly $HP126_assembly

# Generate variant list
show-snps -Clr R7_vs_HP126.delta > R7_vs_HP126.snps