#!/bin/bash -l

#SBATCH -A uppmax2025-3-3
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 16
#SBATCH -t 2:00:00
#SBATCH -J eggnog_annotation
#SBATCH --output=%x.%j.out

set -e

# Load modules
module load bioinfo-tools
module load eggNOG-mapper/2.1.9

R7_proteins="/home/lukasa/Genome_analysis_project/05-annotation/R7_prokka_with_ref_output/R7_with_ref.faa"
HP126_proteins="/home/lukasa/Genome_analysis_project/05-annotation/HP126_prokka_with_ref_output/HP126_with_ref.faa"

# Run eggNOGmapper on the R7 genome
# emapper.py --itype proteins -i $R7_proteins -o R7_eggnog_annotation --cpu 16

# Run eggNOGmapper on the HP126 genome
emapper.py --itype proteins -i $HP126_proteins -o HP126_eggnog_annotation --cpu 16
