#!/bin/bash -l

#SBATCH -A uppmax2025-3-3
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 4
#SBATCH -t 01:00:00
#SBATCH -J prokka_annotation
#SBATCH --output=%x.%j.out

# Load modules
module load bioinfo-tools
module load prokka

set -e

R7_assembly="/home/lukasa/Genome_analysis_project/04-mapping_polishing/polished_assembly_72.fasta"
HP126_assembly="/home/lukasa/Genome_analysis_project/04-mapping_polishing/polished_assembly_66.fasta"

# Run prokka on the R7 strain
prokka --cpus 4 --outdir R7_prokka_output --prefix output_name $R7_assembly

# Run prokka on the HP126 
prokka --cpus 4 --outdir HP126_prokka_output --prefix output_name $HP126_assembly