#!/bin/bash -l

#SBATCH -A uppmax2025-3-3
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 8
#SBATCH -t 06:00:00
#SBATCH -J trim_long_DNA
#SBATCH --mail-type=ALL
#SBATCH --mail-user lukasafgeijerstam@gmail.com
#SBATCH --output=%x.%j.out

# Load modules
module load bioinfo-tools
module load Porechop

set -e

# Input and output directories
input_dir="/home/lukasa/Genome_analysis_project/raw_data/DNA_reads"
output_dir="/home/lukasa/Genome_analysis_project/raw_data/02-trimmed_reads/trimmed_long_reads"

# Run Porechop on each sample
for file in 66 72; do
    input_file="${input_dir}/SRR244130${file}.fastq.gz"
    output_file="${output_dir}/SRR244130${file}_trimmed.fastq.gz"
    porechop -i "$input_file" -o "$output_file" --threads 8
done
