#!/bin/bash -l

#SBATCH -A uppmax2025-3-3
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 6
#SBATCH -t 01:00:00
#SBATCH -J trim_short_DNA
#SBATCH --mail-type=ALL
#SBATCH --mail-user lukasafgeijerstam@gmail.com
#SBATCH --output=%x.%j.out

set -euo pipefail

# Load modules
module load bioinfo-tools
module load trimmomatic

# Input and output directories
input_dir="/home/lukasa/Genome_analysis_project/raw_data/DNA_reads/short_reads"
output_dir="/home/lukasa/Genome_analysis_project/raw_data/02-trimmed_reads/trimmed_short_reads"

# Adapter file (provided with Trimmomatic)
adapters="/sw/bioinfo/trimmomatic/0.39/rackham/adapters/TruSeq3-PE.fa"

# Run Trimmomatic on each sample
for file in 65 71; do
    input_R1="${input_dir}/SRR244130${file}_1.fastq.gz"
    input_R2="${input_dir}/SRR244130${file}_2.fastq.gz"
    
    output_paired_R1="${output_dir}/SRR244130${file}_1_paired.fq.gz"
    output_unpaired_R1="${output_dir}/SRR244130${file}_1_unpaired.fq.gz"
    output_paired_R2="${output_dir}/SRR244130${file}_2_paired.fq.gz"
    output_unpaired_R2="${output_dir}/SRR244130${file}_2_unpaired.fq.gz"
    
    trimmomatic PE -threads 4 -phred33 \
        "$input_R1" "$input_R2" \
        "$output_paired_R1" "$output_unpaired_R1" \
        "$output_paired_R2" "$output_unpaired_R2" \
        ILLUMINACLIP:"$adapters":2:30:10 \
        LEADING:3 TRAILING:20 SLIDINGWINDOW:4:20 MINLEN:150
done
