#!/bin/bash -l

#SBATCH -A uppmax2025-3-3
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 8
#SBATCH -t 03:00:00
#SBATCH -J feature_counts_RNA
#SBATCH --output=%x.%j.out

set -e

# Load modules
module load bioinfo-tools
module load subread

# Annotation files (.gtf format)
R7_annotation_file="/home/lukasa/Genome_analysis_project/05-annotation/R7_prokka_output/R7_annotation.gtf"

# BAM file directory
bam_dir="/home/lukasa/Genome_analysis_project/07-RNA_mapping/against_R7"

# Count features for R7 (all three replicates)
for i in 62 63 64; do
   featureCounts -T 8 -p -s 2 \
   -a "$R7_annotation_file" \
   -o "R7_counts_${i}.txt" \
   -g gene_id \
   -t transcript \
   "$bam_dir/${i}_sorted.bam"
done

# Count features for HP126 (all three replicates)
for i in 59 60 61; do
    featureCounts -T 8 -p -s 2 \
    -a "$R7_annotation_file" \
    -o "HP126_counts_${i}.txt" \
    -g gene_id \
    -t transcript \
    "$bam_dir/${i}_sorted.bam"
done