#!/bin/bash -l

#SBATCH -A uppmax2025-3-3
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 8
#SBATCH -t 01:00:00
#SBATCH -J bwa_mapping_DNA
#SBATCH --output=%x.%j.out

# Load modules
module load bioinfo-tools
module load bwa

set -e

# Input directories
assembly_dir="/home/lukasa/Genome_analysis_project/03-assembly/long_read_assembly_output/SRR244130"
reads_dir="/home/lukasa/Genome_analysis_project/raw_data/02-trimmed_reads/trimmed_short_reads/SRR244130"
output_dir="/home/lukasa/Genome_analysis_project/04-mapping_polishing"

# File paths for first assembly
assembly_file="${assembly_dir}66/assembly.fasta"
reads_file_1="${reads_dir}65_1_paired.fq.gz"
reads_file_2="${reads_dir}65_2_paired.fq.gz"

# Run BWA index and mem for the first assembly
bwa index "$assembly_file"
bwa mem -t 8 "$assembly_file" "$reads_file_1" "$reads_file_2" > "${output_dir}/aln66.sam"

# File paths for second assembly
assembly_file="${assembly_dir}72/assembly.fasta"
reads_file_1="${reads_dir}71_1_paired.fq.gz"
reads_file_2="${reads_dir}71_2_paired.fq.gz"

# Run BWA index and mem for the second assembly
bwa index "$assembly_file"
bwa mem -t 8 "$assembly_file" "$reads_file_1" "$reads_file_2" > "${output_dir}/aln72.sam"
