!/bin/bash -l

#SBATCH -A uppmax2025-3-3
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 8
#SBATCH -t 01:00:00
#SBATCH -J quast_assembled_DNA
#SBATCH --mail-type=ALL
#SBATCH --mail-user lukasafgeijerstam@gmail.com
#SBATCH --output=%x.%j.out

# Load modules
module load bioinfo-tools
module load quast

set -e

# Input and output directories for HP126
input_file="/home/lukasa/Genome_analysis_project/03-assembly/long_read_assembly_output/SRR24413066/assembly.fasta"
reference_file="/home/lukasa/Genome_analysis_project/raw_data/reference_genome/HP126_genome.fasta"
output_dir="/home/lukasa/Genome_analysis_project/03-assembly/assembly_evaluation/HP126_evaluation"

# Run quast on HP126 file
quast "$input_file" -r "$reference_file" --long -o "$output_dir" --threads 8

# Input and output directories for R7
input_file="/home/lukasa/Genome_analysis_project/03-assembly/long_read_assembly_output/SRR24413072/assembly.fasta"
reference_file="/home/lukasa/Genome_analysis_project/raw_data/reference_genome/R7_genome.fasta"
output_dir="/home/lukasa/Genome_analysis_project/03-assembly/assembly_evaluation/R7_evaluation"

# Run quast on R7 file
quast "$input_file" -r "$reference_file" --long -o "$output_dir" --threads 8
