#!/bin/bash -l

#SBATCH -A uppmax2025-3-3
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 6
#SBATCH -t 01:00:00
#SBATCH -J trim_RNA
#SBATCH --mail-type=ALL
#SBATCH --mail-user lukasafgeijerstam@gmail.com
#SBATCH --output=%x.%j.out

# Load modules
module load bioinfo-tools
module load trimmomatic

# Input and output directories
input_dir="/home/lukasa/Genome_analysis_project/raw_data/RNA_reads"
output_dir="/home/lukasa/Genome_analysis_project/raw_data/02-trimmed_reads"

# Adapter file (provided with Trimmomatic)
adapters="/sw/bioinfo/trimmomatic/0.39/rackham/adapters/TruSeq3-PE.fa"

# Run Trimmomatic on each sample
for file in 59 60 61 62 63 64; do
    input_R1="${input_dir}/SRR245164${file}_1.fastq.gz"
    input_R2="${input_dir}/SRR245164${file}_2.fastq.gz"
    
    output_R1="${output_dir}/SRR245164${file}_1.fq.gz"
    output_R2="${output_dir}/SRR245164${file}_2.fq.gz"
    
    trimmomatic PE -threads 6 -phred33 \
        "$input_R1" "$input_R2" \
        "$output_R1" \
        "$output_R2" \
        ILLUMINACLIP:"$adapters":2:30:10 \
        LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36
done